### ISSUE TITLE
Enhancement: Drop 3.8 support

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/type-lens#44]
### Summary

3.8 typing is weird, and it's EOL. This library is pretty well suited to not impact anyone yet as usage is small, so I think we could drop it with minimal repercussions and shed some syntax weirdness

**Comment by DanCardin** [comment]
I'd really rather not. Cappa currently supports 3.8, mostly because I did see some 3.8 installs last I looked that didn't appear to be CI. I guess they could be my local development... 🤔.

But also, I dont think the 3.8 support is particularly burdensome. 3.8/3.9 together are problematic due to lack of proper `|` syntax, which we have a backport for. but again, it's relevant to 3.9 as well; which is the only real significant old-version mainenance burden as far as I'm concerned.

**Comment by JacobCoffee** [comment]
Sounds good to me! :D
